name: Sync books list metadata.

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '0 6 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: init oss config
        uses: yizhoumo/setup-ossutil@v1
        with:
          ossutil-version: '1.7.3'
          endpoint: ${{secrets.OSS_ENDPOINT}}
          access-key-id: ${{secrets.OSS_ID}}
          access-key-secret: ${{secrets.OSS_SECRET}}
          sts-token: ""
      - name: sync books list metadata.
        run: ossutil sync _books.html oss://${{ secrets.OSS_BUCKET }}/ -f --delete
      - name: Sending Build Status
        if: always()
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          JOB_STATE: ${{ job.status }}
          RUNNER_OS: ${{ runner.os }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
        run: python3 notify.py
