name: Build for edition-guide

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Install mdbook
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          version: latest
          use-tool-cache: true
      - name: Clone edition-guide
        run: git clone https://x-access-token:${GITHUB_TOKEN}@github.com/rust-lang/edition-guide edition-guide-en
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: init oss config
        uses: yizhoumo/setup-ossutil@v1
        with:
          ossutil-version: '1.7.3'
          endpoint: ${{secrets.OSS_ENDPOINT}}
          access-key-id: ${{secrets.OSS_ID}}
          access-key-secret: ${{secrets.OSS_SECRET}}
          sts-token: ""
      - name: Build edition-guide
        run: |
          # Build edition-guide
          mkdir -pv archive/en
          cd edition-guide-en && \
            mdbook build && \
            cp -ar book/* ../archive/en/
          # Upload to oss
          ls -alhtr && \
            cd .. && \
            ossutil sync archive/ oss://${{ secrets.OSS_BUCKET }}/edition-guide/ -f --delete
      - name: Sending Build Status
        if: always()
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          JOB_STATE: ${{ job.status }}
          RUNNER_OS: ${{ runner.os }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
        run: python3 notify.py
